// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// match_reads
List match_reads(IntegerVector regionStart, IntegerVector regionEnd, IntegerVector readStart, IntegerVector readEnd, CharacterVector strand, int fraglen);
RcppExport SEXP profile_match_reads(SEXP regionStartSEXP, SEXP regionEndSEXP, SEXP readStartSEXP, SEXP readEndSEXP, SEXP strandSEXP, SEXP fraglenSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type regionStart(regionStartSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type regionEnd(regionEndSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type readStart(readStartSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type readEnd(readEndSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type strand(strandSEXP );
        Rcpp::traits::input_parameter< int >::type fraglen(fraglenSEXP );
        List __result = match_reads(regionStart, regionEnd, readStart, readEnd, strand, fraglen);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
