##' @importFrom utils data
NULL

##' \code{SegvisData} example of histone marks in CTCF peaks
##' 
##' \code{SegvisData} segvis, generated by calling \code{SegvisData}
##' 
##' @return A \code{SegvisData} object
##' @docType data
##' @name segvis
##' @usage data(segvis)
##' @format SegvisData object
NULL