# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates a list with the matched reads for each regions
#'
#' @param regionStart - start(regions) from GRanges
#' @param regionEnd - end(regions) from GRanges
#' @param readStart - start(reads) from GRanges
#' @param readEnd - end(reads) from GRanges
#' @param strand - as.character(strand(reads)) form GRanges
#' @param fraglen - Numeric value, fragment length
#' @return position in reads vector

match_reads <- function(regionStart, regionEnd, readStart, readEnd, strand, fraglen) {
    .Call('profile_match_reads', PACKAGE = 'profile', regionStart, regionEnd, readStart, readEnd, strand, fraglen)
}

